name: Run Scrapers
on:
  workflow_dispatch
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Purging previous chromedriver installation
        run: sudo apt purge google-chrome-stable
      - name: Installing required packages
        run: pip install -r requirements.txt
      - name: Run scrapers
        run: python src/scraper/scraper_ta.py --csv test -n 10
      - name: Commit and push results
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "103622874+aeluro1@users.noreply.github.com@users.noreply.github.com"
          git add .
          git commit -m "GitHub Action: Run Scrapers"
          git push